name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo $GITHUB_REPOSITORY_OWNER
        env:
          OWNER: "${GITHUB_REPOSITORY_OWNER}/botkube"
