name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER}"
        env:
          OWNER: "${{ env.OWNER }}/botkube"
