name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          echo "OWNER=${{ github.repository.owner}}" >> $GITHUB_ENV
      - name: check
        run: |
          echo ${{ env.OWNER}}
